
static const void *insn_jump_table[] = {
   &&nop_void,
&&nop_double,
&&nop_int,
&&nop_float,
&&aaload_void,
&&aaload_double,
&&aaload_int,
&&aaload_float,
&&aastore_void,
&&aastore_double,
&&aastore_int,
&&aastore_float,
&&aconst_null_void,
&&aconst_null_double,
&&aconst_null_int,
&&aconst_null_float,
&&areturn_void,
&&areturn_double,
&&areturn_int,
&&areturn_float,
&&arraylength_void,
&&arraylength_double,
&&arraylength_int,
&&arraylength_float,
&&athrow_void,
&&athrow_double,
&&athrow_int,
&&athrow_float,
&&baload_void,
&&baload_double,
&&baload_int,
&&baload_float,
&&bastore_void,
&&bastore_double,
&&bastore_int,
&&bastore_float,
&&caload_void,
&&caload_double,
&&caload_int,
&&caload_float,
&&castore_void,
&&castore_double,
&&castore_int,
&&castore_float,
&&d2f_void,
&&d2f_double,
&&d2f_int,
&&d2f_float,
&&d2i_void,
&&d2i_double,
&&d2i_int,
&&d2i_float,
&&d2l_void,
&&d2l_double,
&&d2l_int,
&&d2l_float,
&&dadd_void,
&&dadd_double,
&&dadd_int,
&&dadd_float,
&&daload_void,
&&daload_double,
&&daload_int,
&&daload_float,
&&dastore_void,
&&dastore_double,
&&dastore_int,
&&dastore_float,
&&dcmpg_void,
&&dcmpg_double,
&&dcmpg_int,
&&dcmpg_float,
&&dcmpl_void,
&&dcmpl_double,
&&dcmpl_int,
&&dcmpl_float,
&&ddiv_void,
&&ddiv_double,
&&ddiv_int,
&&ddiv_float,
&&dmul_void,
&&dmul_double,
&&dmul_int,
&&dmul_float,
&&dneg_void,
&&dneg_double,
&&dneg_int,
&&dneg_float,
&&drem_void,
&&drem_double,
&&drem_int,
&&drem_float,
&&dreturn_void,
&&dreturn_double,
&&dreturn_int,
&&dreturn_float,
&&dsub_void,
&&dsub_double,
&&dsub_int,
&&dsub_float,
&&dup_void,
&&dup_double,
&&dup_int,
&&dup_float,
&&dup_x1_void,
&&dup_x1_double,
&&dup_x1_int,
&&dup_x1_float,
&&dup_x2_void,
&&dup_x2_double,
&&dup_x2_int,
&&dup_x2_float,
&&dup2_void,
&&dup2_double,
&&dup2_int,
&&dup2_float,
&&dup2_x1_void,
&&dup2_x1_double,
&&dup2_x1_int,
&&dup2_x1_float,
&&dup2_x2_void,
&&dup2_x2_double,
&&dup2_x2_int,
&&dup2_x2_float,
&&f2d_void,
&&f2d_double,
&&f2d_int,
&&f2d_float,
&&f2i_void,
&&f2i_double,
&&f2i_int,
&&f2i_float,
&&f2l_void,
&&f2l_double,
&&f2l_int,
&&f2l_float,
&&fadd_void,
&&fadd_double,
&&fadd_int,
&&fadd_float,
&&faload_void,
&&faload_double,
&&faload_int,
&&faload_float,
&&fastore_void,
&&fastore_double,
&&fastore_int,
&&fastore_float,
&&fcmpg_void,
&&fcmpg_double,
&&fcmpg_int,
&&fcmpg_float,
&&fcmpl_void,
&&fcmpl_double,
&&fcmpl_int,
&&fcmpl_float,
&&fdiv_void,
&&fdiv_double,
&&fdiv_int,
&&fdiv_float,
&&fmul_void,
&&fmul_double,
&&fmul_int,
&&fmul_float,
&&fneg_void,
&&fneg_double,
&&fneg_int,
&&fneg_float,
&&frem_void,
&&frem_double,
&&frem_int,
&&frem_float,
&&freturn_void,
&&freturn_double,
&&freturn_int,
&&freturn_float,
&&fsub_void,
&&fsub_double,
&&fsub_int,
&&fsub_float,
&&i2b_void,
&&i2b_double,
&&i2b_int,
&&i2b_float,
&&i2c_void,
&&i2c_double,
&&i2c_int,
&&i2c_float,
&&i2d_void,
&&i2d_double,
&&i2d_int,
&&i2d_float,
&&i2f_void,
&&i2f_double,
&&i2f_int,
&&i2f_float,
&&i2l_void,
&&i2l_double,
&&i2l_int,
&&i2l_float,
&&i2s_void,
&&i2s_double,
&&i2s_int,
&&i2s_float,
&&iadd_void,
&&iadd_double,
&&iadd_int,
&&iadd_float,
&&iaload_void,
&&iaload_double,
&&iaload_int,
&&iaload_float,
&&iand_void,
&&iand_double,
&&iand_int,
&&iand_float,
&&iastore_void,
&&iastore_double,
&&iastore_int,
&&iastore_float,
&&idiv_void,
&&idiv_double,
&&idiv_int,
&&idiv_float,
&&imul_void,
&&imul_double,
&&imul_int,
&&imul_float,
&&ineg_void,
&&ineg_double,
&&ineg_int,
&&ineg_float,
&&ior_void,
&&ior_double,
&&ior_int,
&&ior_float,
&&irem_void,
&&irem_double,
&&irem_int,
&&irem_float,
&&ireturn_void,
&&ireturn_double,
&&ireturn_int,
&&ireturn_float,
&&ishl_void,
&&ishl_double,
&&ishl_int,
&&ishl_float,
&&ishr_void,
&&ishr_double,
&&ishr_int,
&&ishr_float,
&&isub_void,
&&isub_double,
&&isub_int,
&&isub_float,
&&iushr_void,
&&iushr_double,
&&iushr_int,
&&iushr_float,
&&ixor_void,
&&ixor_double,
&&ixor_int,
&&ixor_float,
&&l2d_void,
&&l2d_double,
&&l2d_int,
&&l2d_float,
&&l2f_void,
&&l2f_double,
&&l2f_int,
&&l2f_float,
&&l2i_void,
&&l2i_double,
&&l2i_int,
&&l2i_float,
&&ladd_void,
&&ladd_double,
&&ladd_int,
&&ladd_float,
&&laload_void,
&&laload_double,
&&laload_int,
&&laload_float,
&&land_void,
&&land_double,
&&land_int,
&&land_float,
&&lastore_void,
&&lastore_double,
&&lastore_int,
&&lastore_float,
&&lcmp_void,
&&lcmp_double,
&&lcmp_int,
&&lcmp_float,
&&ldiv_void,
&&ldiv_double,
&&ldiv_int,
&&ldiv_float,
&&lmul_void,
&&lmul_double,
&&lmul_int,
&&lmul_float,
&&lneg_void,
&&lneg_double,
&&lneg_int,
&&lneg_float,
&&lor_void,
&&lor_double,
&&lor_int,
&&lor_float,
&&lrem_void,
&&lrem_double,
&&lrem_int,
&&lrem_float,
&&lreturn_void,
&&lreturn_double,
&&lreturn_int,
&&lreturn_float,
&&lshl_void,
&&lshl_double,
&&lshl_int,
&&lshl_float,
&&lshr_void,
&&lshr_double,
&&lshr_int,
&&lshr_float,
&&lsub_void,
&&lsub_double,
&&lsub_int,
&&lsub_float,
&&lushr_void,
&&lushr_double,
&&lushr_int,
&&lushr_float,
&&lxor_void,
&&lxor_double,
&&lxor_int,
&&lxor_float,
&&monitorenter_void,
&&monitorenter_double,
&&monitorenter_int,
&&monitorenter_float,
&&monitorexit_void,
&&monitorexit_double,
&&monitorexit_int,
&&monitorexit_float,
&&pop_void,
&&pop_double,
&&pop_int,
&&pop_float,
&&pop2_void,
&&pop2_double,
&&pop2_int,
&&pop2_float,
&&return_void,
&&return_double,
&&return_int,
&&return_float,
&&saload_void,
&&saload_double,
&&saload_int,
&&saload_float,
&&sastore_void,
&&sastore_double,
&&sastore_int,
&&sastore_float,
&&swap_void,
&&swap_double,
&&swap_int,
&&swap_float,
&&anewarray_void,
&&anewarray_double,
&&anewarray_int,
&&anewarray_float,
&&checkcast_void,
&&checkcast_double,
&&checkcast_int,
&&checkcast_float,
&&getfield_void,
&&getfield_double,
&&getfield_int,
&&getfield_float,
&&getstatic_void,
&&getstatic_double,
&&getstatic_int,
&&getstatic_float,
&&instanceof_void,
&&instanceof_double,
&&instanceof_int,
&&instanceof_float,
&&invokedynamic_void,
&&invokedynamic_double,
&&invokedynamic_int,
&&invokedynamic_float,
&&new_void,
&&new_double,
&&new_int,
&&new_float,
&&putfield_void,
&&putfield_double,
&&putfield_int,
&&putfield_float,
&&putstatic_void,
&&putstatic_double,
&&putstatic_int,
&&putstatic_float,
&&invokevirtual_void,
&&invokevirtual_double,
&&invokevirtual_int,
&&invokevirtual_float,
&&invokespecial_void,
&&invokespecial_double,
&&invokespecial_int,
&&invokespecial_float,
&&invokestatic_void,
&&invokestatic_double,
&&invokestatic_int,
&&invokestatic_float,
&&ldc_void,
&&ldc_double,
&&ldc_int,
&&ldc_float,
&&ldc2_w_void,
&&ldc2_w_double,
&&ldc2_w_int,
&&ldc2_w_float,
&&dload_void,
&&dload_double,
&&dload_int,
&&dload_float,
&&fload_void,
&&fload_double,
&&fload_int,
&&fload_float,
&&iload_void,
&&iload_double,
&&iload_int,
&&iload_float,
&&lload_void,
&&lload_double,
&&lload_int,
&&lload_float,
&&dstore_void,
&&dstore_double,
&&dstore_int,
&&dstore_float,
&&fstore_void,
&&fstore_double,
&&fstore_int,
&&fstore_float,
&&istore_void,
&&istore_double,
&&istore_int,
&&istore_float,
&&lstore_void,
&&lstore_double,
&&lstore_int,
&&lstore_float,
&&aload_void,
&&aload_double,
&&aload_int,
&&aload_float,
&&astore_void,
&&astore_double,
&&astore_int,
&&astore_float,
&&goto_void,
&&goto_double,
&&goto_int,
&&goto_float,
&&jsr_void,
&&jsr_double,
&&jsr_int,
&&jsr_float,
&&if_acmpeq_void,
&&if_acmpeq_double,
&&if_acmpeq_int,
&&if_acmpeq_float,
&&if_acmpne_void,
&&if_acmpne_double,
&&if_acmpne_int,
&&if_acmpne_float,
&&if_icmpeq_void,
&&if_icmpeq_double,
&&if_icmpeq_int,
&&if_icmpeq_float,
&&if_icmpne_void,
&&if_icmpne_double,
&&if_icmpne_int,
&&if_icmpne_float,
&&if_icmplt_void,
&&if_icmplt_double,
&&if_icmplt_int,
&&if_icmplt_float,
&&if_icmpge_void,
&&if_icmpge_double,
&&if_icmpge_int,
&&if_icmpge_float,
&&if_icmpgt_void,
&&if_icmpgt_double,
&&if_icmpgt_int,
&&if_icmpgt_float,
&&if_icmple_void,
&&if_icmple_double,
&&if_icmple_int,
&&if_icmple_float,
&&ifeq_void,
&&ifeq_double,
&&ifeq_int,
&&ifeq_float,
&&ifne_void,
&&ifne_double,
&&ifne_int,
&&ifne_float,
&&iflt_void,
&&iflt_double,
&&iflt_int,
&&iflt_float,
&&ifge_void,
&&ifge_double,
&&ifge_int,
&&ifge_float,
&&ifgt_void,
&&ifgt_double,
&&ifgt_int,
&&ifgt_float,
&&ifle_void,
&&ifle_double,
&&ifle_int,
&&ifle_float,
&&ifnonnull_void,
&&ifnonnull_double,
&&ifnonnull_int,
&&ifnonnull_float,
&&ifnull_void,
&&ifnull_double,
&&ifnull_int,
&&ifnull_float,
&&iconst_void,
&&iconst_double,
&&iconst_int,
&&iconst_float,
&&dconst_void,
&&dconst_double,
&&dconst_int,
&&dconst_float,
&&fconst_void,
&&fconst_double,
&&fconst_int,
&&fconst_float,
&&lconst_void,
&&lconst_double,
&&lconst_int,
&&lconst_float,
&&iinc_void,
&&iinc_double,
&&iinc_int,
&&iinc_float,
&&invokeinterface_void,
&&invokeinterface_double,
&&invokeinterface_int,
&&invokeinterface_float,
&&multianewarray_void,
&&multianewarray_double,
&&multianewarray_int,
&&multianewarray_float,
&&newarray_void,
&&newarray_double,
&&newarray_int,
&&newarray_float,
&&tableswitch_void,
&&tableswitch_double,
&&tableswitch_int,
&&tableswitch_float,
&&lookupswitch_void,
&&lookupswitch_double,
&&lookupswitch_int,
&&lookupswitch_float,
&&ret_void,
&&ret_double,
&&ret_int,
&&ret_float,
&&anewarray_resolved_void,
&&anewarray_resolved_double,
&&anewarray_resolved_int,
&&anewarray_resolved_float,
&&checkcast_resolved_void,
&&checkcast_resolved_double,
&&checkcast_resolved_int,
&&checkcast_resolved_float,
&&instanceof_resolved_void,
&&instanceof_resolved_double,
&&instanceof_resolved_int,
&&instanceof_resolved_float,
&&new_resolved_void,
&&new_resolved_double,
&&new_resolved_int,
&&new_resolved_float,
&&invokevtable_monomorphic_void,
&&invokevtable_monomorphic_double,
&&invokevtable_monomorphic_int,
&&invokevtable_monomorphic_float,
&&invokevtable_polymorphic_void,
&&invokevtable_polymorphic_double,
&&invokevtable_polymorphic_int,
&&invokevtable_polymorphic_float,
&&invokeitable_monomorphic_void,
&&invokeitable_monomorphic_double,
&&invokeitable_monomorphic_int,
&&invokeitable_monomorphic_float,
&&invokeitable_polymorphic_void,
&&invokeitable_polymorphic_double,
&&invokeitable_polymorphic_int,
&&invokeitable_polymorphic_float,
&&invokespecial_resolved_void,
&&invokespecial_resolved_double,
&&invokespecial_resolved_int,
&&invokespecial_resolved_float,
&&invokestatic_resolved_void,
&&invokestatic_resolved_double,
&&invokestatic_resolved_int,
&&invokestatic_resolved_float,
&&invokecallsite_void,
&&invokecallsite_double,
&&invokecallsite_int,
&&invokecallsite_float,
&&invokesigpoly_void,
&&invokesigpoly_double,
&&invokesigpoly_int,
&&invokesigpoly_float,
&&getfield_B_void,
&&getfield_B_double,
&&getfield_B_int,
&&getfield_B_float,
&&getfield_C_void,
&&getfield_C_double,
&&getfield_C_int,
&&getfield_C_float,
&&getfield_S_void,
&&getfield_S_double,
&&getfield_S_int,
&&getfield_S_float,
&&getfield_I_void,
&&getfield_I_double,
&&getfield_I_int,
&&getfield_I_float,
&&getfield_J_void,
&&getfield_J_double,
&&getfield_J_int,
&&getfield_J_float,
&&getfield_F_void,
&&getfield_F_double,
&&getfield_F_int,
&&getfield_F_float,
&&getfield_D_void,
&&getfield_D_double,
&&getfield_D_int,
&&getfield_D_float,
&&getfield_Z_void,
&&getfield_Z_double,
&&getfield_Z_int,
&&getfield_Z_float,
&&getfield_L_void,
&&getfield_L_double,
&&getfield_L_int,
&&getfield_L_float,
&&putfield_B_void,
&&putfield_B_double,
&&putfield_B_int,
&&putfield_B_float,
&&putfield_C_void,
&&putfield_C_double,
&&putfield_C_int,
&&putfield_C_float,
&&putfield_S_void,
&&putfield_S_double,
&&putfield_S_int,
&&putfield_S_float,
&&putfield_I_void,
&&putfield_I_double,
&&putfield_I_int,
&&putfield_I_float,
&&putfield_J_void,
&&putfield_J_double,
&&putfield_J_int,
&&putfield_J_float,
&&putfield_F_void,
&&putfield_F_double,
&&putfield_F_int,
&&putfield_F_float,
&&putfield_D_void,
&&putfield_D_double,
&&putfield_D_int,
&&putfield_D_float,
&&putfield_Z_void,
&&putfield_Z_double,
&&putfield_Z_int,
&&putfield_Z_float,
&&putfield_L_void,
&&putfield_L_double,
&&putfield_L_int,
&&putfield_L_float,
&&getstatic_B_void,
&&getstatic_B_double,
&&getstatic_B_int,
&&getstatic_B_float,
&&getstatic_C_void,
&&getstatic_C_double,
&&getstatic_C_int,
&&getstatic_C_float,
&&getstatic_S_void,
&&getstatic_S_double,
&&getstatic_S_int,
&&getstatic_S_float,
&&getstatic_I_void,
&&getstatic_I_double,
&&getstatic_I_int,
&&getstatic_I_float,
&&getstatic_J_void,
&&getstatic_J_double,
&&getstatic_J_int,
&&getstatic_J_float,
&&getstatic_F_void,
&&getstatic_F_double,
&&getstatic_F_int,
&&getstatic_F_float,
&&getstatic_D_void,
&&getstatic_D_double,
&&getstatic_D_int,
&&getstatic_D_float,
&&getstatic_Z_void,
&&getstatic_Z_double,
&&getstatic_Z_int,
&&getstatic_Z_float,
&&getstatic_L_void,
&&getstatic_L_double,
&&getstatic_L_int,
&&getstatic_L_float,
&&putstatic_B_void,
&&putstatic_B_double,
&&putstatic_B_int,
&&putstatic_B_float,
&&putstatic_C_void,
&&putstatic_C_double,
&&putstatic_C_int,
&&putstatic_C_float,
&&putstatic_S_void,
&&putstatic_S_double,
&&putstatic_S_int,
&&putstatic_S_float,
&&putstatic_I_void,
&&putstatic_I_double,
&&putstatic_I_int,
&&putstatic_I_float,
&&putstatic_J_void,
&&putstatic_J_double,
&&putstatic_J_int,
&&putstatic_J_float,
&&putstatic_F_void,
&&putstatic_F_double,
&&putstatic_F_int,
&&putstatic_F_float,
&&putstatic_D_void,
&&putstatic_D_double,
&&putstatic_D_int,
&&putstatic_D_float,
&&putstatic_Z_void,
&&putstatic_Z_double,
&&putstatic_Z_int,
&&putstatic_Z_float,
&&putstatic_L_void,
&&putstatic_L_double,
&&putstatic_L_int,
&&putstatic_L_float,
&&dsqrt_void,
&&dsqrt_double,
&&dsqrt_int,
&&dsqrt_float,

   &&escape
};

goto *insn_jump_table[jump_to];


nop_void: 
    jump_to = (unsigned)nop_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
nop_double: 
    jump_to = (unsigned)nop_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
nop_int: 
    jump_to = (unsigned)nop_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
nop_float: 
    jump_to = (unsigned)nop_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aaload_void: __builtin_unreachable();

aaload_double: __builtin_unreachable();

aaload_int: 
    jump_to = (unsigned)aaload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aaload_float: __builtin_unreachable();

aastore_void: __builtin_unreachable();

aastore_double: __builtin_unreachable();

aastore_int: 
    jump_to = (unsigned)aastore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aastore_float: __builtin_unreachable();

aconst_null_void: 
    jump_to = (unsigned)aconst_null_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aconst_null_double: 
    jump_to = (unsigned)aconst_null_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aconst_null_int: 
    jump_to = (unsigned)aconst_null_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aconst_null_float: 
    jump_to = (unsigned)aconst_null_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
areturn_void: __builtin_unreachable();

areturn_double: __builtin_unreachable();

areturn_int:
    result.l = areturn_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
areturn_float: __builtin_unreachable();

arraylength_void: __builtin_unreachable();

arraylength_double: __builtin_unreachable();

arraylength_int: 
    jump_to = (unsigned)arraylength_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
arraylength_float: __builtin_unreachable();

athrow_void: __builtin_unreachable();

athrow_double: __builtin_unreachable();

athrow_int: 
    jump_to = (unsigned)athrow_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
athrow_float: __builtin_unreachable();

baload_void: __builtin_unreachable();

baload_double: __builtin_unreachable();

baload_int: 
    jump_to = (unsigned)baload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
baload_float: __builtin_unreachable();

bastore_void: __builtin_unreachable();

bastore_double: __builtin_unreachable();

bastore_int: 
    jump_to = (unsigned)bastore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
bastore_float: __builtin_unreachable();

caload_void: __builtin_unreachable();

caload_double: __builtin_unreachable();

caload_int: 
    jump_to = (unsigned)caload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
caload_float: __builtin_unreachable();

castore_void: __builtin_unreachable();

castore_double: __builtin_unreachable();

castore_int: 
    jump_to = (unsigned)castore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
castore_float: __builtin_unreachable();

d2f_void: __builtin_unreachable();

d2f_double: 
    jump_to = (unsigned)d2f_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
d2f_int: __builtin_unreachable();

d2f_float: __builtin_unreachable();

d2i_void: __builtin_unreachable();

d2i_double: 
    jump_to = (unsigned)d2i_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
d2i_int: __builtin_unreachable();

d2i_float: __builtin_unreachable();

d2l_void: __builtin_unreachable();

d2l_double: 
    jump_to = (unsigned)d2l_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
d2l_int: __builtin_unreachable();

d2l_float: __builtin_unreachable();

dadd_void: __builtin_unreachable();

dadd_double: 
    jump_to = (unsigned)dadd_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dadd_int: __builtin_unreachable();

dadd_float: __builtin_unreachable();

daload_void: __builtin_unreachable();

daload_double: __builtin_unreachable();

daload_int: 
    jump_to = (unsigned)daload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
daload_float: __builtin_unreachable();

dastore_void: __builtin_unreachable();

dastore_double: 
    jump_to = (unsigned)dastore_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dastore_int: __builtin_unreachable();

dastore_float: __builtin_unreachable();

dcmpg_void: __builtin_unreachable();

dcmpg_double: 
    jump_to = (unsigned)dcmpg_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dcmpg_int: __builtin_unreachable();

dcmpg_float: __builtin_unreachable();

dcmpl_void: __builtin_unreachable();

dcmpl_double: 
    jump_to = (unsigned)dcmpl_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dcmpl_int: __builtin_unreachable();

dcmpl_float: __builtin_unreachable();

ddiv_void: __builtin_unreachable();

ddiv_double: 
    jump_to = (unsigned)ddiv_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ddiv_int: __builtin_unreachable();

ddiv_float: __builtin_unreachable();

dmul_void: __builtin_unreachable();

dmul_double: 
    jump_to = (unsigned)dmul_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dmul_int: __builtin_unreachable();

dmul_float: __builtin_unreachable();

dneg_void: __builtin_unreachable();

dneg_double: 
    jump_to = (unsigned)dneg_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dneg_int: __builtin_unreachable();

dneg_float: __builtin_unreachable();

drem_void: __builtin_unreachable();

drem_double: __builtin_unreachable();

drem_int: __builtin_unreachable();

drem_float: __builtin_unreachable();

dreturn_void: __builtin_unreachable();

dreturn_double:
    result.l = dreturn_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
dreturn_int: __builtin_unreachable();

dreturn_float: __builtin_unreachable();

dsub_void: __builtin_unreachable();

dsub_double: 
    jump_to = (unsigned)dsub_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dsub_int: __builtin_unreachable();

dsub_float: __builtin_unreachable();

dup_void: __builtin_unreachable();

dup_double: 
    jump_to = (unsigned)dup_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_int: 
    jump_to = (unsigned)dup_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_float: 
    jump_to = (unsigned)dup_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_x1_void: __builtin_unreachable();

dup_x1_double: 
    jump_to = (unsigned)dup_x1_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_x1_int: 
    jump_to = (unsigned)dup_x1_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_x1_float: 
    jump_to = (unsigned)dup_x1_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_x2_void: __builtin_unreachable();

dup_x2_double: 
    jump_to = (unsigned)dup_x2_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_x2_int: 
    jump_to = (unsigned)dup_x2_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup_x2_float: 
    jump_to = (unsigned)dup_x2_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_void: __builtin_unreachable();

dup2_double: 
    jump_to = (unsigned)dup2_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_int: 
    jump_to = (unsigned)dup2_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_float: 
    jump_to = (unsigned)dup2_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_x1_void: __builtin_unreachable();

dup2_x1_double: 
    jump_to = (unsigned)dup2_x1_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_x1_int: 
    jump_to = (unsigned)dup2_x1_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_x1_float: 
    jump_to = (unsigned)dup2_x1_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_x2_void: __builtin_unreachable();

dup2_x2_double: 
    jump_to = (unsigned)dup2_x2_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_x2_int: 
    jump_to = (unsigned)dup2_x2_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dup2_x2_float: 
    jump_to = (unsigned)dup2_x2_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
f2d_void: __builtin_unreachable();

f2d_double: __builtin_unreachable();

f2d_int: __builtin_unreachable();

f2d_float: 
    jump_to = (unsigned)f2d_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
f2i_void: __builtin_unreachable();

f2i_double: __builtin_unreachable();

f2i_int: __builtin_unreachable();

f2i_float: 
    jump_to = (unsigned)f2i_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
f2l_void: __builtin_unreachable();

f2l_double: __builtin_unreachable();

f2l_int: __builtin_unreachable();

f2l_float: 
    jump_to = (unsigned)f2l_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fadd_void: __builtin_unreachable();

fadd_double: __builtin_unreachable();

fadd_int: __builtin_unreachable();

fadd_float: 
    jump_to = (unsigned)fadd_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
faload_void: __builtin_unreachable();

faload_double: __builtin_unreachable();

faload_int: 
    jump_to = (unsigned)faload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
faload_float: __builtin_unreachable();

fastore_void: __builtin_unreachable();

fastore_double: __builtin_unreachable();

fastore_int: __builtin_unreachable();

fastore_float: 
    jump_to = (unsigned)fastore_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fcmpg_void: __builtin_unreachable();

fcmpg_double: __builtin_unreachable();

fcmpg_int: __builtin_unreachable();

fcmpg_float: 
    jump_to = (unsigned)fcmpg_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fcmpl_void: __builtin_unreachable();

fcmpl_double: __builtin_unreachable();

fcmpl_int: __builtin_unreachable();

fcmpl_float: 
    jump_to = (unsigned)fcmpl_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fdiv_void: __builtin_unreachable();

fdiv_double: __builtin_unreachable();

fdiv_int: __builtin_unreachable();

fdiv_float: 
    jump_to = (unsigned)fdiv_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fmul_void: __builtin_unreachable();

fmul_double: __builtin_unreachable();

fmul_int: __builtin_unreachable();

fmul_float: 
    jump_to = (unsigned)fmul_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fneg_void: __builtin_unreachable();

fneg_double: __builtin_unreachable();

fneg_int: __builtin_unreachable();

fneg_float: 
    jump_to = (unsigned)fneg_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
frem_void: __builtin_unreachable();

frem_double: __builtin_unreachable();

frem_int: __builtin_unreachable();

frem_float: __builtin_unreachable();

freturn_void: __builtin_unreachable();

freturn_double: __builtin_unreachable();

freturn_int: __builtin_unreachable();

freturn_float:
    result.l = freturn_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
fsub_void: __builtin_unreachable();

fsub_double: __builtin_unreachable();

fsub_int: __builtin_unreachable();

fsub_float: 
    jump_to = (unsigned)fsub_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2b_void: __builtin_unreachable();

i2b_double: __builtin_unreachable();

i2b_int: 
    jump_to = (unsigned)i2b_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2b_float: __builtin_unreachable();

i2c_void: __builtin_unreachable();

i2c_double: __builtin_unreachable();

i2c_int: 
    jump_to = (unsigned)i2c_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2c_float: __builtin_unreachable();

i2d_void: __builtin_unreachable();

i2d_double: __builtin_unreachable();

i2d_int: 
    jump_to = (unsigned)i2d_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2d_float: __builtin_unreachable();

i2f_void: __builtin_unreachable();

i2f_double: __builtin_unreachable();

i2f_int: 
    jump_to = (unsigned)i2f_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2f_float: __builtin_unreachable();

i2l_void: __builtin_unreachable();

i2l_double: __builtin_unreachable();

i2l_int: 
    jump_to = (unsigned)i2l_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2l_float: __builtin_unreachable();

i2s_void: __builtin_unreachable();

i2s_double: __builtin_unreachable();

i2s_int: 
    jump_to = (unsigned)i2s_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
i2s_float: __builtin_unreachable();

iadd_void: __builtin_unreachable();

iadd_double: __builtin_unreachable();

iadd_int: 
    jump_to = (unsigned)iadd_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iadd_float: __builtin_unreachable();

iaload_void: __builtin_unreachable();

iaload_double: __builtin_unreachable();

iaload_int: 
    jump_to = (unsigned)iaload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iaload_float: __builtin_unreachable();

iand_void: __builtin_unreachable();

iand_double: __builtin_unreachable();

iand_int: 
    jump_to = (unsigned)iand_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iand_float: __builtin_unreachable();

iastore_void: __builtin_unreachable();

iastore_double: __builtin_unreachable();

iastore_int: 
    jump_to = (unsigned)iastore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iastore_float: __builtin_unreachable();

idiv_void: __builtin_unreachable();

idiv_double: __builtin_unreachable();

idiv_int: 
    jump_to = (unsigned)idiv_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
idiv_float: __builtin_unreachable();

imul_void: __builtin_unreachable();

imul_double: __builtin_unreachable();

imul_int: 
    jump_to = (unsigned)imul_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
imul_float: __builtin_unreachable();

ineg_void: __builtin_unreachable();

ineg_double: __builtin_unreachable();

ineg_int: 
    jump_to = (unsigned)ineg_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ineg_float: __builtin_unreachable();

ior_void: __builtin_unreachable();

ior_double: __builtin_unreachable();

ior_int: 
    jump_to = (unsigned)ior_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ior_float: __builtin_unreachable();

irem_void: __builtin_unreachable();

irem_double: __builtin_unreachable();

irem_int: 
    jump_to = (unsigned)irem_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
irem_float: __builtin_unreachable();

ireturn_void: __builtin_unreachable();

ireturn_double: __builtin_unreachable();

ireturn_int:
    result.l = ireturn_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
ireturn_float: __builtin_unreachable();

ishl_void: __builtin_unreachable();

ishl_double: __builtin_unreachable();

ishl_int: 
    jump_to = (unsigned)ishl_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ishl_float: __builtin_unreachable();

ishr_void: __builtin_unreachable();

ishr_double: __builtin_unreachable();

ishr_int: 
    jump_to = (unsigned)ishr_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ishr_float: __builtin_unreachable();

isub_void: __builtin_unreachable();

isub_double: __builtin_unreachable();

isub_int: 
    jump_to = (unsigned)isub_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
isub_float: __builtin_unreachable();

iushr_void: __builtin_unreachable();

iushr_double: __builtin_unreachable();

iushr_int: 
    jump_to = (unsigned)iushr_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iushr_float: __builtin_unreachable();

ixor_void: __builtin_unreachable();

ixor_double: __builtin_unreachable();

ixor_int: 
    jump_to = (unsigned)ixor_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ixor_float: __builtin_unreachable();

l2d_void: __builtin_unreachable();

l2d_double: __builtin_unreachable();

l2d_int: 
    jump_to = (unsigned)l2d_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
l2d_float: __builtin_unreachable();

l2f_void: __builtin_unreachable();

l2f_double: __builtin_unreachable();

l2f_int: 
    jump_to = (unsigned)l2f_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
l2f_float: __builtin_unreachable();

l2i_void: __builtin_unreachable();

l2i_double: __builtin_unreachable();

l2i_int: 
    jump_to = (unsigned)l2i_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
l2i_float: __builtin_unreachable();

ladd_void: __builtin_unreachable();

ladd_double: __builtin_unreachable();

ladd_int: 
    jump_to = (unsigned)ladd_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ladd_float: __builtin_unreachable();

laload_void: __builtin_unreachable();

laload_double: __builtin_unreachable();

laload_int: 
    jump_to = (unsigned)laload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
laload_float: __builtin_unreachable();

land_void: __builtin_unreachable();

land_double: __builtin_unreachable();

land_int: 
    jump_to = (unsigned)land_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
land_float: __builtin_unreachable();

lastore_void: __builtin_unreachable();

lastore_double: __builtin_unreachable();

lastore_int: 
    jump_to = (unsigned)lastore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lastore_float: __builtin_unreachable();

lcmp_void: __builtin_unreachable();

lcmp_double: __builtin_unreachable();

lcmp_int: 
    jump_to = (unsigned)lcmp_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lcmp_float: __builtin_unreachable();

ldiv_void: __builtin_unreachable();

ldiv_double: __builtin_unreachable();

ldiv_int: 
    jump_to = (unsigned)ldiv_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ldiv_float: __builtin_unreachable();

lmul_void: __builtin_unreachable();

lmul_double: __builtin_unreachable();

lmul_int: 
    jump_to = (unsigned)lmul_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lmul_float: __builtin_unreachable();

lneg_void: __builtin_unreachable();

lneg_double: __builtin_unreachable();

lneg_int: 
    jump_to = (unsigned)lneg_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lneg_float: __builtin_unreachable();

lor_void: __builtin_unreachable();

lor_double: __builtin_unreachable();

lor_int: 
    jump_to = (unsigned)lor_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lor_float: __builtin_unreachable();

lrem_void: __builtin_unreachable();

lrem_double: __builtin_unreachable();

lrem_int: 
    jump_to = (unsigned)lrem_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lrem_float: __builtin_unreachable();

lreturn_void: __builtin_unreachable();

lreturn_double: __builtin_unreachable();

lreturn_int:
    result.l = lreturn_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
lreturn_float: __builtin_unreachable();

lshl_void: __builtin_unreachable();

lshl_double: __builtin_unreachable();

lshl_int: 
    jump_to = (unsigned)lshl_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lshl_float: __builtin_unreachable();

lshr_void: __builtin_unreachable();

lshr_double: __builtin_unreachable();

lshr_int: 
    jump_to = (unsigned)lshr_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lshr_float: __builtin_unreachable();

lsub_void: __builtin_unreachable();

lsub_double: __builtin_unreachable();

lsub_int: 
    jump_to = (unsigned)lsub_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lsub_float: __builtin_unreachable();

lushr_void: __builtin_unreachable();

lushr_double: __builtin_unreachable();

lushr_int: 
    jump_to = (unsigned)lushr_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lushr_float: __builtin_unreachable();

lxor_void: __builtin_unreachable();

lxor_double: __builtin_unreachable();

lxor_int: 
    jump_to = (unsigned)lxor_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lxor_float: __builtin_unreachable();

monitorenter_void: __builtin_unreachable();

monitorenter_double: __builtin_unreachable();

monitorenter_int: 
    jump_to = (unsigned)monitorenter_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
monitorenter_float: __builtin_unreachable();

monitorexit_void: __builtin_unreachable();

monitorexit_double: __builtin_unreachable();

monitorexit_int: 
    jump_to = (unsigned)monitorexit_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
monitorexit_float: __builtin_unreachable();

pop_void: 
    jump_to = (unsigned)pop_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
pop_double: 
    jump_to = (unsigned)pop_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
pop_int: 
    jump_to = (unsigned)pop_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
pop_float: 
    jump_to = (unsigned)pop_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
pop2_void: __builtin_unreachable();

pop2_double: 
    jump_to = (unsigned)pop2_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
pop2_int: 
    jump_to = (unsigned)pop2_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
pop2_float: 
    jump_to = (unsigned)pop2_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
return_void:
    result.l = return_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
return_double:
    result.l = return_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
return_int:
    result.l = return_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
return_float:
    result.l = return_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);;
    goto done;
saload_void: __builtin_unreachable();

saload_double: __builtin_unreachable();

saload_int: 
    jump_to = (unsigned)saload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
saload_float: __builtin_unreachable();

sastore_void: __builtin_unreachable();

sastore_double: __builtin_unreachable();

sastore_int: 
    jump_to = (unsigned)sastore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
sastore_float: __builtin_unreachable();

swap_void: __builtin_unreachable();

swap_double: 
    jump_to = (unsigned)swap_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
swap_int: 
    jump_to = (unsigned)swap_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
swap_float: 
    jump_to = (unsigned)swap_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
anewarray_void: __builtin_unreachable();

anewarray_double: __builtin_unreachable();

anewarray_int: 
    jump_to = (unsigned)anewarray_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
anewarray_float: __builtin_unreachable();

checkcast_void: __builtin_unreachable();

checkcast_double: __builtin_unreachable();

checkcast_int: 
    jump_to = (unsigned)checkcast_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
checkcast_float: __builtin_unreachable();

getfield_void: __builtin_unreachable();

getfield_double: __builtin_unreachable();

getfield_int: 
    jump_to = (unsigned)getfield_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_float: __builtin_unreachable();

getstatic_void: 
    jump_to = (unsigned)getstatic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_double: 
    jump_to = (unsigned)getstatic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_int: 
    jump_to = (unsigned)getstatic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_float: 
    jump_to = (unsigned)getstatic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
instanceof_void: __builtin_unreachable();

instanceof_double: __builtin_unreachable();

instanceof_int: 
    jump_to = (unsigned)instanceof_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
instanceof_float: __builtin_unreachable();

invokedynamic_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokedynamic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokedynamic_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokedynamic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokedynamic_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokedynamic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokedynamic_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokedynamic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
new_void: 
    jump_to = (unsigned)new_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
new_double: 
    jump_to = (unsigned)new_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
new_int: 
    jump_to = (unsigned)new_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
new_float: 
    jump_to = (unsigned)new_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_void: __builtin_unreachable();

putfield_double: 
    jump_to = (unsigned)putfield_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_int: 
    jump_to = (unsigned)putfield_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_float: 
    jump_to = (unsigned)putfield_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_void: __builtin_unreachable();

putstatic_double: 
    jump_to = (unsigned)putstatic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_int: 
    jump_to = (unsigned)putstatic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_float: 
    jump_to = (unsigned)putstatic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokevirtual_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevirtual_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokevirtual_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevirtual_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokevirtual_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevirtual_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokevirtual_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevirtual_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokespecial_void: __builtin_unreachable();

invokespecial_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokespecial_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokespecial_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokespecial_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokespecial_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokespecial_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokestatic_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokestatic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokestatic_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokestatic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokestatic_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokestatic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokestatic_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokestatic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
ldc_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)ldc_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
ldc_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)ldc_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
ldc_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)ldc_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
ldc_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)ldc_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
ldc2_w_void: 
    jump_to = (unsigned)ldc2_w_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ldc2_w_double: 
    jump_to = (unsigned)ldc2_w_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ldc2_w_int: 
    jump_to = (unsigned)ldc2_w_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ldc2_w_float: 
    jump_to = (unsigned)ldc2_w_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dload_void: 
    jump_to = (unsigned)dload_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dload_double: 
    jump_to = (unsigned)dload_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dload_int: 
    jump_to = (unsigned)dload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dload_float: 
    jump_to = (unsigned)dload_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fload_void: 
    jump_to = (unsigned)fload_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fload_double: 
    jump_to = (unsigned)fload_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fload_int: 
    jump_to = (unsigned)fload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fload_float: 
    jump_to = (unsigned)fload_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iload_void: 
    jump_to = (unsigned)iload_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iload_double: 
    jump_to = (unsigned)iload_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iload_int: 
    jump_to = (unsigned)iload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iload_float: 
    jump_to = (unsigned)iload_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lload_void: 
    jump_to = (unsigned)lload_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lload_double: 
    jump_to = (unsigned)lload_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lload_int: 
    jump_to = (unsigned)lload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lload_float: 
    jump_to = (unsigned)lload_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dstore_void: __builtin_unreachable();

dstore_double: 
    jump_to = (unsigned)dstore_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dstore_int: __builtin_unreachable();

dstore_float: __builtin_unreachable();

fstore_void: __builtin_unreachable();

fstore_double: __builtin_unreachable();

fstore_int: __builtin_unreachable();

fstore_float: 
    jump_to = (unsigned)fstore_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
istore_void: __builtin_unreachable();

istore_double: __builtin_unreachable();

istore_int: 
    jump_to = (unsigned)istore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
istore_float: __builtin_unreachable();

lstore_void: __builtin_unreachable();

lstore_double: __builtin_unreachable();

lstore_int: 
    jump_to = (unsigned)lstore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lstore_float: __builtin_unreachable();

aload_void: 
    jump_to = (unsigned)aload_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aload_double: 
    jump_to = (unsigned)aload_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aload_int: 
    jump_to = (unsigned)aload_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
aload_float: 
    jump_to = (unsigned)aload_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
astore_void: __builtin_unreachable();

astore_double: __builtin_unreachable();

astore_int: 
    jump_to = (unsigned)astore_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
astore_float: __builtin_unreachable();

goto_void: 
    jump_to = (unsigned)goto_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
goto_double: 
    jump_to = (unsigned)goto_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
goto_int: 
    jump_to = (unsigned)goto_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
goto_float: 
    jump_to = (unsigned)goto_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
jsr_void: __builtin_unreachable();

jsr_double: __builtin_unreachable();

jsr_int: __builtin_unreachable();

jsr_float: __builtin_unreachable();

if_acmpeq_void: __builtin_unreachable();

if_acmpeq_double: __builtin_unreachable();

if_acmpeq_int: 
    jump_to = (unsigned)if_acmpeq_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_acmpeq_float: __builtin_unreachable();

if_acmpne_void: __builtin_unreachable();

if_acmpne_double: __builtin_unreachable();

if_acmpne_int: 
    jump_to = (unsigned)if_acmpne_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_acmpne_float: __builtin_unreachable();

if_icmpeq_void: __builtin_unreachable();

if_icmpeq_double: __builtin_unreachable();

if_icmpeq_int: 
    jump_to = (unsigned)if_icmpeq_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_icmpeq_float: __builtin_unreachable();

if_icmpne_void: __builtin_unreachable();

if_icmpne_double: __builtin_unreachable();

if_icmpne_int: 
    jump_to = (unsigned)if_icmpne_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_icmpne_float: __builtin_unreachable();

if_icmplt_void: __builtin_unreachable();

if_icmplt_double: __builtin_unreachable();

if_icmplt_int: 
    jump_to = (unsigned)if_icmplt_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_icmplt_float: __builtin_unreachable();

if_icmpge_void: __builtin_unreachable();

if_icmpge_double: __builtin_unreachable();

if_icmpge_int: 
    jump_to = (unsigned)if_icmpge_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_icmpge_float: __builtin_unreachable();

if_icmpgt_void: __builtin_unreachable();

if_icmpgt_double: __builtin_unreachable();

if_icmpgt_int: 
    jump_to = (unsigned)if_icmpgt_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_icmpgt_float: __builtin_unreachable();

if_icmple_void: __builtin_unreachable();

if_icmple_double: __builtin_unreachable();

if_icmple_int: 
    jump_to = (unsigned)if_icmple_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
if_icmple_float: __builtin_unreachable();

ifeq_void: __builtin_unreachable();

ifeq_double: __builtin_unreachable();

ifeq_int: 
    jump_to = (unsigned)ifeq_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifeq_float: __builtin_unreachable();

ifne_void: __builtin_unreachable();

ifne_double: __builtin_unreachable();

ifne_int: 
    jump_to = (unsigned)ifne_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifne_float: __builtin_unreachable();

iflt_void: __builtin_unreachable();

iflt_double: __builtin_unreachable();

iflt_int: 
    jump_to = (unsigned)iflt_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iflt_float: __builtin_unreachable();

ifge_void: __builtin_unreachable();

ifge_double: __builtin_unreachable();

ifge_int: 
    jump_to = (unsigned)ifge_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifge_float: __builtin_unreachable();

ifgt_void: __builtin_unreachable();

ifgt_double: __builtin_unreachable();

ifgt_int: 
    jump_to = (unsigned)ifgt_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifgt_float: __builtin_unreachable();

ifle_void: __builtin_unreachable();

ifle_double: __builtin_unreachable();

ifle_int: 
    jump_to = (unsigned)ifle_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifle_float: __builtin_unreachable();

ifnonnull_void: __builtin_unreachable();

ifnonnull_double: __builtin_unreachable();

ifnonnull_int: 
    jump_to = (unsigned)ifnonnull_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifnonnull_float: __builtin_unreachable();

ifnull_void: __builtin_unreachable();

ifnull_double: __builtin_unreachable();

ifnull_int: 
    jump_to = (unsigned)ifnull_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
ifnull_float: __builtin_unreachable();

iconst_void: 
    jump_to = (unsigned)iconst_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iconst_double: 
    jump_to = (unsigned)iconst_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iconst_int: 
    jump_to = (unsigned)iconst_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iconst_float: 
    jump_to = (unsigned)iconst_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dconst_void: 
    jump_to = (unsigned)dconst_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dconst_double: 
    jump_to = (unsigned)dconst_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dconst_int: 
    jump_to = (unsigned)dconst_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dconst_float: 
    jump_to = (unsigned)dconst_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fconst_void: 
    jump_to = (unsigned)fconst_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fconst_double: 
    jump_to = (unsigned)fconst_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fconst_int: 
    jump_to = (unsigned)fconst_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
fconst_float: 
    jump_to = (unsigned)fconst_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lconst_void: 
    jump_to = (unsigned)lconst_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lconst_double: 
    jump_to = (unsigned)lconst_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lconst_int: 
    jump_to = (unsigned)lconst_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lconst_float: 
    jump_to = (unsigned)lconst_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iinc_void: 
    jump_to = (unsigned)iinc_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iinc_double: 
    jump_to = (unsigned)iinc_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iinc_int: 
    jump_to = (unsigned)iinc_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
iinc_float: 
    jump_to = (unsigned)iinc_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokeinterface_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeinterface_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeinterface_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeinterface_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeinterface_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeinterface_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeinterface_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeinterface_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
multianewarray_void: __builtin_unreachable();

multianewarray_double: __builtin_unreachable();

multianewarray_int: 
    jump_to = (unsigned)multianewarray_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
multianewarray_float: __builtin_unreachable();

newarray_void: __builtin_unreachable();

newarray_double: __builtin_unreachable();

newarray_int: 
    jump_to = (unsigned)newarray_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
newarray_float: __builtin_unreachable();

tableswitch_void: __builtin_unreachable();

tableswitch_double: __builtin_unreachable();

tableswitch_int: 
    jump_to = (unsigned)tableswitch_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
tableswitch_float: __builtin_unreachable();

lookupswitch_void: __builtin_unreachable();

lookupswitch_double: __builtin_unreachable();

lookupswitch_int: 
    jump_to = (unsigned)lookupswitch_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
lookupswitch_float: __builtin_unreachable();

ret_void: __builtin_unreachable();

ret_double: __builtin_unreachable();

ret_int: __builtin_unreachable();

ret_float: __builtin_unreachable();

anewarray_resolved_void: __builtin_unreachable();

anewarray_resolved_double: __builtin_unreachable();

anewarray_resolved_int: 
    jump_to = (unsigned)anewarray_resolved_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
anewarray_resolved_float: __builtin_unreachable();

checkcast_resolved_void: __builtin_unreachable();

checkcast_resolved_double: __builtin_unreachable();

checkcast_resolved_int: 
    jump_to = (unsigned)checkcast_resolved_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
checkcast_resolved_float: __builtin_unreachable();

instanceof_resolved_void: __builtin_unreachable();

instanceof_resolved_double: __builtin_unreachable();

instanceof_resolved_int: 
    jump_to = (unsigned)instanceof_resolved_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
instanceof_resolved_float: __builtin_unreachable();

new_resolved_void: 
    jump_to = (unsigned)new_resolved_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
new_resolved_double: 
    jump_to = (unsigned)new_resolved_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
new_resolved_int: 
    jump_to = (unsigned)new_resolved_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
new_resolved_float: 
    jump_to = (unsigned)new_resolved_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokevtable_monomorphic_void: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokevtable_monomorphic_double: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokevtable_monomorphic_int: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokevtable_monomorphic_float: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokevtable_polymorphic_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevtable_polymorphic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokevtable_polymorphic_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevtable_polymorphic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokevtable_polymorphic_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevtable_polymorphic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokevtable_polymorphic_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokevtable_polymorphic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeitable_monomorphic_void: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokeitable_monomorphic_double: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokeitable_monomorphic_int: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokeitable_monomorphic_float: 
    jump_to = (unsigned)invokeitable_vtable_monomorphic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokeitable_polymorphic_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeitable_polymorphic_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeitable_polymorphic_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeitable_polymorphic_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeitable_polymorphic_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeitable_polymorphic_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokeitable_polymorphic_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokeitable_polymorphic_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokespecial_resolved_void: 
    jump_to = (unsigned)invokespecial_resolved_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokespecial_resolved_double: 
    jump_to = (unsigned)invokespecial_resolved_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokespecial_resolved_int: 
    jump_to = (unsigned)invokespecial_resolved_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokespecial_resolved_float: 
    jump_to = (unsigned)invokespecial_resolved_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokestatic_resolved_void: 
    jump_to = (unsigned)invokestatic_resolved_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokestatic_resolved_double: 
    jump_to = (unsigned)invokestatic_resolved_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokestatic_resolved_int: 
    jump_to = (unsigned)invokestatic_resolved_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokestatic_resolved_float: 
    jump_to = (unsigned)invokestatic_resolved_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokecallsite_void: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokecallsite_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokecallsite_double: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokecallsite_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokecallsite_int: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokecallsite_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokecallsite_float: int_tos_ = int_tos; float_tos_ = float_tos; double_tos_ = double_tos;
    jump_to = (unsigned)invokecallsite_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos_, &float_tos_, &double_tos_);; int_tos = int_tos_; float_tos = float_tos_; double_tos = double_tos_;
    continue;
invokesigpoly_void: 
    jump_to = (unsigned)invokesigpoly_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokesigpoly_double: 
    jump_to = (unsigned)invokesigpoly_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokesigpoly_int: 
    jump_to = (unsigned)invokesigpoly_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
invokesigpoly_float: 
    jump_to = (unsigned)invokesigpoly_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_B_void: __builtin_unreachable();

getfield_B_double: __builtin_unreachable();

getfield_B_int: 
    jump_to = (unsigned)getfield_B_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_B_float: __builtin_unreachable();

getfield_C_void: __builtin_unreachable();

getfield_C_double: __builtin_unreachable();

getfield_C_int: 
    jump_to = (unsigned)getfield_C_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_C_float: __builtin_unreachable();

getfield_S_void: __builtin_unreachable();

getfield_S_double: __builtin_unreachable();

getfield_S_int: 
    jump_to = (unsigned)getfield_S_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_S_float: __builtin_unreachable();

getfield_I_void: __builtin_unreachable();

getfield_I_double: __builtin_unreachable();

getfield_I_int: 
    jump_to = (unsigned)getfield_I_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_I_float: __builtin_unreachable();

getfield_J_void: __builtin_unreachable();

getfield_J_double: __builtin_unreachable();

getfield_J_int: 
    jump_to = (unsigned)getfield_J_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_J_float: __builtin_unreachable();

getfield_F_void: __builtin_unreachable();

getfield_F_double: __builtin_unreachable();

getfield_F_int: 
    jump_to = (unsigned)getfield_F_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_F_float: __builtin_unreachable();

getfield_D_void: __builtin_unreachable();

getfield_D_double: __builtin_unreachable();

getfield_D_int: 
    jump_to = (unsigned)getfield_D_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_D_float: __builtin_unreachable();

getfield_Z_void: __builtin_unreachable();

getfield_Z_double: __builtin_unreachable();

getfield_Z_int: 
    jump_to = (unsigned)getfield_Z_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_Z_float: __builtin_unreachable();

getfield_L_void: __builtin_unreachable();

getfield_L_double: __builtin_unreachable();

getfield_L_int: 
    jump_to = (unsigned)getfield_L_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getfield_L_float: __builtin_unreachable();

putfield_B_void: __builtin_unreachable();

putfield_B_double: __builtin_unreachable();

putfield_B_int: 
    jump_to = (unsigned)putfield_B_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_B_float: __builtin_unreachable();

putfield_C_void: __builtin_unreachable();

putfield_C_double: __builtin_unreachable();

putfield_C_int: 
    jump_to = (unsigned)putfield_C_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_C_float: __builtin_unreachable();

putfield_S_void: __builtin_unreachable();

putfield_S_double: __builtin_unreachable();

putfield_S_int: 
    jump_to = (unsigned)putfield_S_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_S_float: __builtin_unreachable();

putfield_I_void: __builtin_unreachable();

putfield_I_double: __builtin_unreachable();

putfield_I_int: 
    jump_to = (unsigned)putfield_I_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_I_float: __builtin_unreachable();

putfield_J_void: __builtin_unreachable();

putfield_J_double: __builtin_unreachable();

putfield_J_int: 
    jump_to = (unsigned)putfield_J_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_J_float: __builtin_unreachable();

putfield_F_void: __builtin_unreachable();

putfield_F_double: __builtin_unreachable();

putfield_F_int: __builtin_unreachable();

putfield_F_float: 
    jump_to = (unsigned)putfield_F_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_D_void: __builtin_unreachable();

putfield_D_double: 
    jump_to = (unsigned)putfield_D_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_D_int: __builtin_unreachable();

putfield_D_float: __builtin_unreachable();

putfield_Z_void: __builtin_unreachable();

putfield_Z_double: __builtin_unreachable();

putfield_Z_int: 
    jump_to = (unsigned)putfield_Z_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_Z_float: __builtin_unreachable();

putfield_L_void: __builtin_unreachable();

putfield_L_double: __builtin_unreachable();

putfield_L_int: 
    jump_to = (unsigned)putfield_L_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putfield_L_float: __builtin_unreachable();

getstatic_B_void: 
    jump_to = (unsigned)getstatic_B_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_B_double: 
    jump_to = (unsigned)getstatic_B_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_B_int: 
    jump_to = (unsigned)getstatic_B_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_B_float: 
    jump_to = (unsigned)getstatic_B_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_C_void: 
    jump_to = (unsigned)getstatic_C_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_C_double: 
    jump_to = (unsigned)getstatic_C_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_C_int: 
    jump_to = (unsigned)getstatic_C_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_C_float: 
    jump_to = (unsigned)getstatic_C_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_S_void: 
    jump_to = (unsigned)getstatic_S_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_S_double: 
    jump_to = (unsigned)getstatic_S_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_S_int: 
    jump_to = (unsigned)getstatic_S_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_S_float: 
    jump_to = (unsigned)getstatic_S_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_I_void: 
    jump_to = (unsigned)getstatic_I_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_I_double: 
    jump_to = (unsigned)getstatic_I_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_I_int: 
    jump_to = (unsigned)getstatic_I_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_I_float: 
    jump_to = (unsigned)getstatic_I_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_J_void: 
    jump_to = (unsigned)getstatic_J_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_J_double: 
    jump_to = (unsigned)getstatic_J_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_J_int: 
    jump_to = (unsigned)getstatic_J_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_J_float: 
    jump_to = (unsigned)getstatic_J_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_F_void: 
    jump_to = (unsigned)getstatic_F_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_F_double: 
    jump_to = (unsigned)getstatic_F_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_F_int: 
    jump_to = (unsigned)getstatic_F_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_F_float: 
    jump_to = (unsigned)getstatic_F_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_D_void: 
    jump_to = (unsigned)getstatic_D_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_D_double: 
    jump_to = (unsigned)getstatic_D_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_D_int: 
    jump_to = (unsigned)getstatic_D_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_D_float: 
    jump_to = (unsigned)getstatic_D_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_Z_void: 
    jump_to = (unsigned)getstatic_Z_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_Z_double: 
    jump_to = (unsigned)getstatic_Z_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_Z_int: 
    jump_to = (unsigned)getstatic_Z_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_Z_float: 
    jump_to = (unsigned)getstatic_Z_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_L_void: 
    jump_to = (unsigned)getstatic_L_impl_void(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_L_double: 
    jump_to = (unsigned)getstatic_L_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_L_int: 
    jump_to = (unsigned)getstatic_L_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
getstatic_L_float: 
    jump_to = (unsigned)getstatic_L_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_B_void: __builtin_unreachable();

putstatic_B_double: __builtin_unreachable();

putstatic_B_int: 
    jump_to = (unsigned)putstatic_B_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_B_float: __builtin_unreachable();

putstatic_C_void: __builtin_unreachable();

putstatic_C_double: __builtin_unreachable();

putstatic_C_int: 
    jump_to = (unsigned)putstatic_C_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_C_float: __builtin_unreachable();

putstatic_S_void: __builtin_unreachable();

putstatic_S_double: __builtin_unreachable();

putstatic_S_int: 
    jump_to = (unsigned)putstatic_S_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_S_float: __builtin_unreachable();

putstatic_I_void: __builtin_unreachable();

putstatic_I_double: __builtin_unreachable();

putstatic_I_int: 
    jump_to = (unsigned)putstatic_I_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_I_float: __builtin_unreachable();

putstatic_J_void: __builtin_unreachable();

putstatic_J_double: __builtin_unreachable();

putstatic_J_int: 
    jump_to = (unsigned)putstatic_J_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_J_float: __builtin_unreachable();

putstatic_F_void: __builtin_unreachable();

putstatic_F_double: __builtin_unreachable();

putstatic_F_int: __builtin_unreachable();

putstatic_F_float: 
    jump_to = (unsigned)putstatic_F_impl_float(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_D_void: __builtin_unreachable();

putstatic_D_double: 
    jump_to = (unsigned)putstatic_D_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_D_int: __builtin_unreachable();

putstatic_D_float: __builtin_unreachable();

putstatic_Z_void: __builtin_unreachable();

putstatic_Z_double: __builtin_unreachable();

putstatic_Z_int: 
    jump_to = (unsigned)putstatic_Z_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_Z_float: __builtin_unreachable();

putstatic_L_void: __builtin_unreachable();

putstatic_L_double: __builtin_unreachable();

putstatic_L_int: 
    jump_to = (unsigned)putstatic_L_impl_int(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
putstatic_L_float: __builtin_unreachable();

dsqrt_void: __builtin_unreachable();

dsqrt_double: 
    jump_to = (unsigned)dsqrt_impl_double(thread, frame_, &current, &pc_, &sp_, &int_tos, &float_tos, &double_tos);; 
    continue;
dsqrt_int: __builtin_unreachable();

dsqrt_float: __builtin_unreachable();

escape:
break;
